
server:
  port: 8086

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}  #Set via Environment variables
    password: ${MAIL_PASSWORD}  #Set via Environment variables
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
